# Generated by Django 3.1.3 on 2021-01-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('patch', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
    ]
